#!/usr/bin/python3
"""Configure and run Qwen, then ensure the attempt has a minimal report.

The provider owns transcript capture. Like the Hermes wrapper, the full identity
in the prompt instructs the agent to write report.yaml against CompletionClaimV1;
we never manufacture a successful claim from the CLI's final prose.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path


def write_settings(home: Path, context_length: int, max_output_tokens: int = 32_000) -> None:
    if context_length <= 0:
        raise ValueError("Qwen context length must be positive")
    directory = home / ".qwen"
    directory.mkdir(parents=True, exist_ok=True)
    # generationConfig lives under model in Qwen 0.25.0. Its OpenAI generator
    # clamps max_tokens to the room left in this full engine window, including
    # its output margin, rather than adding 32000 to an unbounded input budget.
    settings = {
        "tools": {"shell": {"enableInteractiveShell": False}, "useBuiltinRipgrep": False},
        "model": {
            "maxToolCallsPerTurn": 0,
            "generationConfig": {
                "contextWindowSize": context_length,
                "samplingParams": {"max_tokens": max_output_tokens},
                "extra_body": {"chat_template_kwargs": {"enable_thinking": False}},
            },
        },
        "memory": {
            "enableManagedAutoMemory": False,
            "enableManagedAutoDream": False,
            "enableAutoSkill": False,
            "enableTeamMemory": False,
            "enableTeamMemorySync": False,
        },
        "skills": {"disabledLevels": ["project", "user", "extension", "bundled"]},
    }
    (directory / "settings.json").write_text(json.dumps(settings) + "\n", encoding="utf-8")


def launch_argv(argv: list[str], identity: Path) -> list[str]:
    text = identity.read_text(encoding="utf-8").strip()
    if not text:
        raise ValueError("Qwen identity must not be empty")
    return ["/usr/local/bin/qwen", *argv[:-1], f"{text}\n\n{argv[-1]}"]


def _commands(transcript: Path) -> list[str]:
    commands: list[str] = []
    try:
        lines = transcript.read_text(encoding="utf-8").splitlines()
    except OSError:
        return commands
    for line in lines:
        try:
            event = json.loads(line)
        except json.JSONDecodeError:
            continue
        blocks = (event.get("message") or {}).get("content") or []
        for block in blocks:
            value = (block.get("input") or {}).get("command") if isinstance(block, dict) else None
            if isinstance(value, str) and value not in commands:
                commands.append(value)
    return commands


def write_minimal_report(report_dir: Path, identity: Path, exit_code: int) -> None:
    if (report_dir / "report.yaml").exists() or (report_dir / "blocked.md").exists():
        return
    report_dir.mkdir(parents=True, exist_ok=True)
    identity_text = identity.read_text(encoding="utf-8")
    criteria = list(dict.fromkeys(re.findall(r"`?(AC\d+)`?", identity_text)))
    try:
        commits = subprocess.run(
            ["git", "log", "--format=%H", "origin/main..HEAD"],
            check=False,
            capture_output=True,
            text=True,
        ).stdout.splitlines()
    except OSError:
        commits = []
    commands = _commands(report_dir / "transcript.jsonl")
    status = "completed" if exit_code == 0 else f"exited with code {exit_code}"
    mapping = [
        {"id": item, "status": "not_exercised", "evidence": "generated from the run log"}
        for item in criteria
    ]
    document = {
        "schema_version": "1.0",
        "summary": f"Qwen {status}; {len(commits)} commit(s), {len(commands)} command(s).",
        "self_review": {
            "documentation": ["Generated by the Qwen wrapper because no report was written."],
            "acceptance_criteria": mapping,
            "omissions": ["The worker did not write a completion report."],
        },
        "acceptance_mapping": mapping,
        "proposed_pull_request": {"title": "Qwen worker changes", "body": status},
        "limitations": [],
        "risks": [],
        "blockers": [],
        "follow_ups": [],
        "run_evidence": [f"command: {command}" for command in commands]
        + [f"commit: {commit}" for commit in commits],
    }
    (report_dir / "report.yaml").write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    identity = Path(os.environ["CRUCIBLE_QWEN_IDENTITY"])
    write_settings(
        Path.home(),
        int(os.environ["CRUCIBLE_QWEN_CONTEXT_LENGTH"]),
        int(os.environ.get("CRUCIBLE_QWEN_MAX_OUTPUT_TOKENS", "32000")),
    )
    argv = launch_argv(sys.argv[1:], identity)
    completed = subprocess.run(argv, check=False)
    write_minimal_report(
        Path(os.environ["CRUCIBLE_QWEN_REPORT_DIR"]), identity, completed.returncode
    )
    raise SystemExit(completed.returncode)


if __name__ == "__main__":
    main()
