"""Event kinds (10). Kinds are an enum; adding one is a migration."""

from __future__ import annotations

from enum import StrEnum

PRINCIPAL_CRUCIBLE = "crucible"
# A webhook delivery has no authenticated principal and is not the supervisor's write:
# events about one are recorded under GitHub's own name, which is also what keeps them
# outside the fenced set (14).
PRINCIPAL_GITHUB = "github"
# A worker's own progress lines are recorded under its name and never verified (07):
# they are claims the worker made about itself, ingested as data.
PRINCIPAL_WORKER = "worker"


class EventKind(StrEnum):
    # task
    TASK_SUBMITTED = "task_submitted"
    # hades #424: a proposal and the operator's answers to it.
    TASK_PROPOSED = "task_proposed"
    TASK_APPROVED = "task_approved"
    TASK_SENT_BACK = "task_sent_back"
    TASK_PROPOSAL_REJECTED = "task_proposal_rejected"
    TASK_SCHEDULED = "task_scheduled"
    TASK_RUNNING = "task_running"
    TASK_REPORTED = "task_reported"
    TASK_BLOCKED = "task_blocked"
    TASK_CANCEL_REQUESTED = "task_cancel_requested"
    TASK_CANCELLING = "task_cancelling"
    TASK_CANCELLED = "task_cancelled"
    TASK_RETRY_SCHEDULED = "task_retry_scheduled"
    TRANSITION_REJECTED = "transition_rejected"
    CONTRACT_REJECTED = "contract_rejected"
    # execution
    EXECUTION_CREATED = "execution_created"
    EXECUTION_ACTIVE = "execution_active"
    EXECUTION_SUCCEEDED = "execution_succeeded"
    EXECUTION_FAILED = "execution_failed"
    EXECUTION_CANCELLED = "execution_cancelled"
    EXECUTION_RESUMED = "execution_resumed"
    # attempt
    ATTEMPT_CREATED = "attempt_created"
    ATTEMPT_PREPARING = "attempt_preparing"
    ATTEMPT_LAUNCHING = "attempt_launching"
    ATTEMPT_RUNNING = "attempt_running"
    ATTEMPT_TIMEOUT_DRAIN = "attempt_timeout_drain"
    ATTEMPT_TIMEOUT_KILL = "attempt_timeout_kill"
    ATTEMPT_CANCEL_KILL = "attempt_cancel_kill"
    ATTEMPT_TERMINATING = "attempt_terminating"
    ATTEMPT_EXITED = "attempt_exited"
    ATTEMPT_LOST = "attempt_lost"
    ATTEMPT_COLLECTED = "attempt_collected"
    ATTEMPT_SUCCEEDED = "attempt_succeeded"
    ATTEMPT_BLOCKED = "attempt_blocked"
    ATTEMPT_FAILED = "attempt_failed"
    ATTEMPT_ADOPTED = "attempt_adopted"
    ATTEMPT_LOGS_DRAINED = "attempt_logs_drained"
    ATTEMPT_CLEANED_UP = "attempt_cleaned_up"
    WORKSPACE_PREPARED = "workspace_prepared"
    CHECKOUT_LEASE_TAKEN = "checkout_lease_taken"
    CHECKOUT_LEASE_DENIED = "checkout_lease_denied"
    CHECKOUT_LEASE_RELEASED = "checkout_lease_released"
    IMAGE_RESOLVED = "image_resolved"
    COLLECTOR_REJECTED_FILE = "collector_rejected_file"
    COLLECTION_FAILED = "collection_failed"
    VERIFICATION_COMPLETED = "verification_completed"
    REPORT_PARSED = "report_parsed"
    REPORT_PARSE_FAILED = "report_parse_failed"
    # gates, evidence, claims
    EVIDENCE_RECORDED = "evidence_recorded"
    GATES_EVALUATED = "gates_evaluated"
    GATE_RESULT_RECORDED = "gate_result_recorded"
    ARTIFACT_STORED = "artifact_stored"
    ARTIFACT_REJECTED = "artifact_rejected"
    # internal review
    TASK_AWAITING_INTERNAL_REVIEW = "task_awaiting_internal_review"
    REVIEW_EXECUTION_REQUESTED = "review_execution_requested"
    REVIEW_REPORT_RECORDED = "review_report_recorded"
    REVIEW_REPORT_REJECTED = "review_report_rejected"
    # gates outcome
    TASK_GATES_PASSED = "task_gates_passed"
    TASK_PRE_PR_GATES_FAILED = "task_pre_pr_gates_failed"
    TASK_AWAITING_ACCEPTANCE = "task_awaiting_acceptance"
    # acceptance, corrections, decisions
    ACCEPTANCE_RECORDED = "acceptance_recorded"
    TASK_ACCEPTED = "task_accepted"
    TASK_REJECTED = "task_rejected"
    TASK_PUBLISH_PENDING = "task_publish_pending"
    TASK_AMENDED = "task_amended"
    TASK_CORRECTION_ATTACHED = "task_correction_attached"
    TASK_CLOSED = "task_closed"
    DECISION_RECORDED = "decision_recorded"
    # hades #489: an operator's note on a task, and a phase action applied from the
    # board card with that note as the decision's verbatim.
    TASK_NOTE_RECORDED = "task_note_recorded"
    TASK_PHASE_ACTION_APPLIED = "task_phase_action_applied"
    # hades #208 item 2: the supervisor's evidence that a note reached the worker (it was
    # in an attempt's identity) and that the worker addressed it (its report named it).
    TASK_NOTE_ACKNOWLEDGED = "task_note_acknowledged"
    TASK_NOTE_ACTED_ON = "task_note_acted_on"
    # hades #208 item 2: a worker's question as a record, and its answer.
    MINION_QUESTION_ASKED = "minion_question_asked"
    MINION_QUESTION_ANSWERED = "minion_question_answered"
    # hades #208 item 2: during bootstrap, Foundry hands a decision or an action (accept,
    # merge, cancel, reroute) to Hades or Hades hands one to Foundry; the event carries
    # the principal, the local time and the words.
    HANDOFF_RECORDED = "handoff_recorded"
    # hades #208: the shared memory store and the decision ledger. A promotion makes a
    # finding memory; a supersede replaces an item; a forget retires one with no
    # replacement; a ledger line is a principal's words recorded through POST /decisions.
    MEMORY_PROMOTED = "memory_promoted"
    MEMORY_SUPERSEDED = "memory_superseded"
    MEMORY_FORGOTTEN = "memory_forgotten"
    LEDGER_DECISION_RECORDED = "ledger_decision_recorded"
    DISPOSITION_RECORDED = "disposition_recorded"
    DISPOSITION_INVALIDATED = "disposition_invalidated"
    ESCALATION_OPENED = "escalation_opened"
    ESCALATION_ANSWERED = "escalation_answered"
    ESCALATION_CLOSED = "escalation_closed"
    # wakes
    WAKE_CREATED = "wake_created"
    WAKE_DELIVERED = "wake_delivered"
    WAKE_DELIVERY_FAILED = "wake_delivery_failed"
    WAKE_DELIVERY_ABANDONED = "wake_delivery_abandoned"
    WAKE_ACKED = "wake_acked"
    # policies and routing
    POLICY_UPLOADED = "policy_uploaded"
    ROUTING_POLICY_UPLOADED = "routing_policy_uploaded"
    QUOTA_RESERVED = "quota_reserved"
    QUOTA_EXHAUSTED = "quota_exhausted"
    POOL_EXHAUSTED = "pool_exhausted"
    POOL_EXHAUSTION_CLEARED = "pool_exhaustion_cleared"
    ATTEMPT_ROUTED = "attempt_routed"
    TASK_REROUTED = "task_rerouted"
    TASK_AWAITING_QUOTA = "task_awaiting_quota"
    TASK_QUOTA_RESUMED = "task_quota_resumed"
    QUOTA_WIP_COMMITTED = "quota_wip_committed"
    ATTEMPT_METRICS_RECORDED = "attempt_metrics_recorded"
    # supervisor
    SUPERVISOR_LEASE_ACQUIRED = "supervisor_lease_acquired"
    SUPERVISOR_LEASE_RELEASED = "supervisor_lease_released"
    ORPHAN_REMOVED = "orphan_removed"
    RETENTION_APPLIED = "retention_applied"
    # publication (23)
    TASK_PUBLISHING = "task_publishing"
    PUBLISH_STARTED = "publish_started"
    INSTALLATION_TOKEN_MINTED = "installation_token_minted"
    PUBLISHER_STARTED = "publisher_started"
    PUBLISHER_FINISHED = "publisher_finished"
    BRANCH_PUSHED = "branch_pushed"
    PULL_REQUEST_OPENED = "pull_request_opened"
    PULL_REQUEST_HEAD_UPDATED = "pull_request_head_updated"
    EXTERNAL_REVIEW_REQUESTED = "external_review_requested"
    PUBLISH_COMPLETED = "publish_completed"
    TASK_PUBLISH_FAILED = "task_publish_failed"
    TASK_AWAITING_EXTERNAL_REVIEW = "task_awaiting_external_review"
    TASK_AWAITING_CI_CERTIFICATION = "task_awaiting_ci_certification"
    # observation (23)
    PULL_REQUEST_POLLED = "pull_request_polled"
    PULL_REQUEST_STATE_CHANGED = "pull_request_state_changed"
    PULL_REQUEST_HEAD_OBSERVED = "pull_request_head_observed"
    REACTIONS_UNOBSERVABLE = "reactions_unobservable"
    REACTION_RECEIVED = "reaction_received"
    REACTION_REMOVED = "reaction_removed"
    EXTERNAL_REVIEW_RECEIVED = "external_review_received"
    REVIEW_COMMENT_RECEIVED = "review_comment_received"
    ISSUE_COMMENT_RECEIVED = "issue_comment_received"
    EXTERNAL_REVIEW_IGNORED = "external_review_ignored"
    EXTERNAL_REVIEW_CYCLE_OPENED = "external_review_cycle_opened"
    EXTERNAL_REVIEW_CYCLE_COMPLETED = "external_review_cycle_completed"
    EXTERNAL_REVIEW_TRIGGER_NEEDED = "external_review_trigger_needed"
    TASK_EXTERNAL_FEEDBACK_RECEIVED = "task_external_feedback_received"
    CHECK_RUN_OBSERVED = "check_run_observed"
    WORKFLOW_RUN_OBSERVED = "workflow_run_observed"
    CI_CERTIFICATION_RECORDED = "ci_certification_recorded"
    TASK_CI_CERTIFICATION_FAILED = "task_ci_certification_failed"
    CI_DECISION_RECORDED = "ci_decision_recorded"
    TASK_READY_FOR_MERGE = "task_ready_for_merge"
    TASK_MERGED = "task_merged"
    TASK_HEAD_DIVERGED = "task_head_diverged"
    HEAD_DECISION_RECORDED = "head_decision_recorded"
    SUPERSEDED_FOR_HEAD = "superseded_for_head"
    GITHUB_DELIVERY_RECEIVED = "github_delivery_received"
    GITHUB_DELIVERY_REJECTED = "github_delivery_rejected"
    GITHUB_RATE_LIMITED = "github_rate_limited"
    # hades #443: the images-digest workflow's own commit on the work branch is Hades's
    # head move, not divergence; the publisher builds on it.
    DIGEST_COMMIT_OBSERVED = "digest_commit_observed"
    # harness administration and credentials (07, 12, 25)
    HARNESS_REFUSED = "harness_refused"
    HARNESS_LAUNCH_DEFERRED = "harness_launch_deferred"
    HARNESS_ENABLED = "harness_enabled"
    HARNESS_DISABLED = "harness_disabled"
    CREDENTIAL_SYNCED = "credential_synced"
    CREDENTIAL_REFRESHED = "credential_refreshed"
    CREDENTIAL_REFRESH_FAILED = "credential_refresh_failed"
    WORKER_PROGRESS = "worker_progress"
    WORKER_QUIET = "worker_quiet"
    WORKER_STALLED = "worker_stalled"
    # administration (25): every mutation, with principal, reason, before and after
    STATUS_CACHE_UPDATED = "status_cache_updated"
    AUTO_MERGE_UPDATED = "auto_merge_updated"
    CREDENTIAL_VALIDATED = "credential_validated"
    CREDENTIAL_PROBED = "credential_probed"
    CREDENTIAL_SET = "credential_set"
    CREDENTIAL_LOGIN_STARTED = "credential_login_started"
    CREDENTIAL_LOGIN_CODE_SUBMITTED = "credential_login_code_submitted"
    CREDENTIAL_LOGIN_CANCELLED = "credential_login_cancelled"
    CREDENTIAL_LOGIN_FINISHED = "credential_login_finished"
    CREDENTIAL_ROTATED = "credential_rotated"
    CREDENTIAL_REMOVED = "credential_removed"
    CREDENTIAL_REFRESH_REQUESTED = "credential_refresh_requested"
    CREDENTIAL_RETIRED_SHREDDED = "credential_retired_shredded"
    CREDENTIAL_MOUNT_MODE_SET = "credential_mount_mode_set"
    IMAGE_PROMOTED = "image_promoted"
    GITHUB_CHECKED = "github_checked"
    ADMIN_REFUSED = "admin_refused"
    LOCAL_ENDPOINT_UPDATED = "local_endpoint_updated"
    KUBERNETES_EGRESS_UPDATED = "kubernetes_egress_updated"
    KUBERNETES_TIMEOUTS_UPDATED = "kubernetes_timeouts_updated"
    # the first-run setup (crucible#119, #120, #121): the gateway URL and its models,
    # and the GitHub App credential the service now owns (ADR 0017)
    LOCAL_GATEWAY_UPDATED = "local_gateway_updated"
    GITHUB_APP_CONNECTED = "github_app_connected"
    # the one-click App (crucible#168): a start of the manifest flow and the saved
    # external URL its redirect uses
    GITHUB_APP_MANIFEST_STARTED = "github_app_manifest_started"
    GITHUB_EXTERNAL_URL_UPDATED = "github_external_url_updated"
    COMMAND_TIMEOUT_UPDATED = "command_timeout_updated"
    # the bootstrap ledger handoff (15, C6)
    BOOTSTRAP_IMPORT_VERIFIED = "bootstrap_import_verified"
    BOOTSTRAP_IMPORT_COMMITTED = "bootstrap_import_committed"
    BOOTSTRAP_TASK_IMPORTED = "bootstrap_task_imported"
    BOOTSTRAP_EVENT_IMPORTED = "bootstrap_event_imported"
    BOOTSTRAP_HANDOFF = "bootstrap_handoff"
    # a verified import withdrawn before it was committed (ADR 0029)
    BOOTSTRAP_IMPORT_DISCARDED = "bootstrap_import_discarded"
    # principals and configuration
    PRINCIPAL_CREATED = "principal_created"
    PRINCIPAL_REVOKED = "principal_revoked"
    PRINCIPAL_RENAMED = "principal_renamed"
    REPOSITORY_REGISTERED = "repository_registered"
    REPOSITORY_BATCH_REGISTERED = "repository_batch_registered"
    REPOSITORY_REBOUND = "repository_rebound"
    REPOSITORY_REMOVED = "repository_removed"
    REPOSITORY_ATTESTATION_RECORDED = "repository_attestation_recorded"
